server:
  port: 8092

auth:
  host: localhost
  realm: master
  issuer-uri: "http://${auth.host}:8080/auth/realms/${auth.realm}"
  jwk-set-uri: "${auth.issuer-uri}/protocol/openid-connect/certs"
  user-name-attribute: preferred_username

api:
  url: "http://${auth.host}:8089/testinfo"

opa:
  url: "http://${auth.host}:8181/v1/data/http/authz/allow"

#spring:
#  security:
#    oauth2:
#      resourceserver:
#        id: keycloak
#        jwt:
#          issuer-uri: ${auth.issuer-uri}
#          jwk-set-uri: "${auth.issuer-uri}/protocol/openid-connect/certs"


logging:
  level:
    org:
      springframework:
        security: DEBUG