server:
  port: 8092

auth:
  host: localhost
  realm: master
  issuer-uri: "http://${auth.host}:8080/auth/realms/${auth.realm}"
  jwk-set-uri: "${auth.issuer-uri}/protocol/openid-connect/certs"
  user-name-attribute: preferred_username

multi-tenant:
  tenants:
    - issuerUri: "http://${auth.host}:8080/auth/realms/master"
      jwkSetUri: "http://${auth.host}:8080/auth/realms/master/protocol/openid-connect/certs"
    - issuerUri: "http://${auth.host}:8080/auth/realms/x-realm"
      jwkSetUri: "http://${auth.host}:8080/auth/realms/x-realm/protocol/openid-connect/certs"


api:
  url: "http://${auth.host}:8089/testinfo"

opa:
  url: "http://${auth.host}:8181/v1/data/http/authz/allow"


logging:
  level:
    org:
      springframework:
        security: DEBUG