server:
  port: 8092

auth:
  host: localhost
  realm: master
  issuer-uri: "http://${auth.host}:8080/auth/realms/${auth.realm}"
  user-name-attribute: preferred_username

opa:
  url: "http://${auth.host}:8181/v1/data/http/authz/allow"

spring:
  security:
    oauth2:
      resourceserver:
        id: keycloak
        jwt:
          issuer-uri: ${auth.issuer-uri}
          jwk-set-uri: "${auth.issuer-uri}/protocol/openid-connect/certs"


logging:
  level:
    org:
      springframework:
        security: DEBUG